 name: screen_mirror_app
 description: A new Flutter project for screen mirroring.
 version: 1.0.0+1

 environment:
   sdk: '>=3.0.0 <4.0.0'

 dependencies:
   flutter:
     sdk: flutter
   flutter_webrtc: ^0.12.1
   permission_handler: ^11.3.1

 dev_dependencies:
   flutter_test:
     sdk: flutter

 flutter:
   uses-material-design: true
