    1 name: Build Flutter APK
    2 on:
    3   push:
    4     branches:
    5       - main
    6   pull_request:
    7     branches:
    8       - main
    9
   10 jobs:
   11   build:
   12     runs-on: ubuntu-latest
   13     steps:
   14       - name: Checkout code
   15         uses: actions/checkout@v3
   16
   17       - name: Setup Java
   18         uses: actions/setup-java@v3
   19         with:
   20           distribution: 'zulu'
   21           java-version: '17'
   22
   23       - name: Setup Flutter
   24         uses: subosito/flutter-action@v2
   25         with:
   26           channel: 'stable'
   27
   28       - name: Get dependencies
   29         run: flutter pub get
   30
   31       - name: Build Release APK
   32         run: flutter build apk --release
   33
   34       - name: Save APK to Artifacts
   35         uses: actions/upload-artifact@v3
   36         with:
   37           name: app-release
   38           path: build/app/outputs/flutter-apk/app-release.apk
