 name: Build APK
 on: [push, pull_request]
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

       - name: Setup Java
         uses: actions/setup-java@v4
         with:
           distribution: 'oracle'
           java-version: '17'

       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           channel: 'stable'

       - name: Create Real Flutter Project
         run: |
           # 1. Naya project banayen
           flutter create --platforms android my_app
           # 2. Hamari main.dart file ko project mein copy karein
           cp lib/main.dart my_app/lib/main.dart
           # 3. Dependencies add karein
           cd my_app
           flutter pub add flutter_webrtc permission_handler

       - name: Build APK
         run: |
           cd my_app
           flutter build apk --release

       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: app-release
           path: my_app/build/app/outputs/flutter-apk/app-release.apk
